//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VideoCableWeb.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CajasDistribucione
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CajasDistribucione()
        {
            this.ClientesCajasDistribucionesServicios = new HashSet<ClientesCajasDistribucionesServicio>();
        }
    
        public int CajaDistribucionId { get; set; }
        public string Descipcion { get; set; }
        public string Longitud { get; set; }
        public string Latitud { get; set; }
        public System.DateTime FechaUltimaModificacion { get; set; }
        public string UsuarioUltimaModificacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientesCajasDistribucionesServicio> ClientesCajasDistribucionesServicios { get; set; }
    }
}
