//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VideoCableWeb.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientesCajasDistribucionesServicio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ClientesCajasDistribucionesServicio()
        {
            this.ClientesCajasDistribucionesServiciosEstados = new HashSet<ClientesCajasDistribucionesServiciosEstado>();
        }
    
        public int ClienteCajaDistribucionServicioId { get; set; }
        public int ClienteId { get; set; }
        public int CajaDistribucionId { get; set; }
        public int ServicioId { get; set; }
        public Nullable<int> UltimoEstadoId { get; set; }
        public System.DateTime FechaUltimaModificacion { get; set; }
        public string UsuarioUltimaModificacion { get; set; }
    
        public virtual CajasDistribucione CajasDistribucione { get; set; }
        public virtual Cliente Cliente { get; set; }
        public virtual Estado Estado { get; set; }
        public virtual Servicio Servicio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientesCajasDistribucionesServiciosEstado> ClientesCajasDistribucionesServiciosEstados { get; set; }
    }
}
