//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VideoCableWeb.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientesCajasDistribucionesServiciosEstado
    {
        public int ClienteCajaDistribucionServicioEstadoId { get; set; }
        public int ClienteCajaDistribucionServicioId { get; set; }
        public int EstadoId { get; set; }
        public System.DateTime FechaUltimaModificacion { get; set; }
        public string UsuarioUltimaModificacion { get; set; }
    
        public virtual Estado Estado { get; set; }
        public virtual ClientesCajasDistribucionesServicio ClientesCajasDistribucionesServicio { get; set; }
    }
}
